name: 🚀 Deploy NestJS to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Copiar proyecto al VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        port: 22
        source: "."
        target: "/home/${{ secrets.VPS_USER }}/app"

    - name: Ejecutar comandos en el VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        port: 22
        script: |
          cd /home/${{ secrets.VPS_USER }}/app
          echo "$${{ secrets.ENV_FILE }}" > .env
          npm install
          npm run build
          pm2 restart nest-app || pm2 start dist/main.js --name nest-app
